singleNamespace: false
workflow:
  serviceAccount:
    create: true
    labels: {}
    annotations: {}
    name: "argo-workflow"
    pullSecrets: []
  rbac:
    create: true
    serviceAccounts:
      - name: default
controller:
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    namespace: ""
  workflowNamespaces:
    - workflows
    - argo
    - argo-events
  logging:
    level: info
    globallevel: "0"
    format: "text"
executor:
  autoscaling:
    enabled: true
  logging:
    level: info
    globallevel: "0"
    format: "text"
server:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
  logging:
    level: info
    globallevel: "0"
    format: "text"
  authModes:
    - server
useStaticCredentials: true
artifactRepository:
  archiveLogs: false
  s3:
    bucket: my-bucket # Create this bucket in MinIO
    endpoint: argo-artifacts.argo.svc:9000
    insecure: true
    accessKeySecret:
      name: "argo-artifacts"
      key: rootUser
    secretKeySecret:
      name: "argo-artifacts"
      key: rootPassword
