mode: standalone

fullnameOverride: argo-artifacts

persistence:
  size: 4Gi

resources:
  requests:
    memory: 512Mi
    cpu: 250m

# Default access keys (change for production)
rootUser: minioadmin
rootPassword: minioadmin

service:
  type: ClusterIP

# Disable TLS for testing
tls:
  enabled: false
