[project]
name = "argo-hera"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "debugpy>=1.8.14",
    "faker>=37.1.0",
    "hera>=5.20.1",
    "httpx>=0.28.1",
    "pydantic>=2.11.4",
    "pytest>=8.3.5",
]
